name: CI

on:
  push:
    branches:
      - '**'
      - '!**.tmp'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v5
      - name: Check formatting
        run: cargo fmt -- --check --config group_imports=StdExternalCrate
      - name: Clippy
        run: cargo clippy --tests -- -D warnings
      - name: Detect Cargo.lock changes
        run: git diff-index --quiet HEAD --
      - name: markdownlint
        run: markdownlint *.md

  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
